<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?= $_SESSION['name']?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->allTweetsUser->total_tweets ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->allFollowing->total_following ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->view->allFollowers->total_followers ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form action="/tweet" method="post">
						<textarea name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button type="submit" class="btn btn-primary">Tweet</button>
						</div>

					</form>
				</div>
			</div>

			<?php foreach ($this->view->tweets as $key => $tweet) { ?>
				
				<div class="row tweet">
					<div class="col">
						<p><strong><?= $tweet->name ?></strong> <span class="text text-muted">- <?= $tweet->date ?></span></p>
						<p><?= $tweet->tweet ?></p>

						<br />
						<?php if($tweet->user_id == $_SESSION['id']) { ?>
							<div class="col d-flex justify-content-end">
								<a href="/removeTweet?removeTweet=<?=$tweet->id?>" class="btn btn-danger">
									<small>Remover</small>
								</a>
							</div>
						<?php } ?>
					</div>
				</div>
			<?php } ?>

			<div class="row mt-4 d-flex justify-content-between">
				<nav>
					<ul class="pagination pagination-sm">
						<li class="page-item">
							<a href="?page=1" class="page-link">
								<span>&laquo;</span>
								<span class="sr-only">Anterior</span> 
							</a>
						</li>

						<?php for($cont = 1; $cont <= $this->view->totalPages; $cont++) {?>
							<li class="page-item">
								<a href="?page=<?=$cont?>" class="page-link"><?= $cont ?></a>
							</li>
						<?php } ?>

						<li class="page-item">
							<a href="?page=<?=$this->view->totalPages?>" class="page-link">
								<span>&raquo;</span>
								<span class="sr-only">Próximo</span>
							</a>
						</li>
					</ul>
				</nav>
				<div>
					-
				</div>
			</div>
		</div>

		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quemSeguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>